class·Solution:
····def·findMaxConsecutiveOnes(self,·nums:·List[int])·->·int:
········count·=·temp·=·0
········for·i·in·nums:
············if·i·==·1:
················temp·+=·1
············else:
················count·=·max(count,·temp)
················temp·=·0
········count·=·max(count,·temp)
········return·count
········
[
